const tailwindConfig = require('../../tailwind.config.js');
// const tailwindConfig = {
//   theme: {
//     extend: {
//       colors: {
//         current: 'currentColor',
//         transparent: 'transparent',
//         'text-base': '#ffffff',
//         primary: '#454cbf',
//         secondary: '#c57c85',
//         accent: '#422a68',
//         black: '#000000',
//         grey: '#6A727F',
//         grey_0: '#4a4a4a',
//         grey_1: '#707070',
//         light_1: '#ebebeb',
//         white: '#ffffff',
//         background: '#ffffff',
//         light_white: '#f4f6f6',
//         red: {
//           DEFAULT: '#ff0000',
//         },
//         orange: '#ffae1a',
//         mono: '#754c00',
//         'border-red': '#ff0000',
//         bgGrey: '#808080',
//         stroke: '#E2E8F0',
//         boxdark: '#24303F',
//         'boxdark-2': '#1A222C',
//         strokedark: '#2E3A47',
//         content: '#000000',
//         'form-strokedark': '#3d4d60',
//         'form-input': '#1d2a39',
//         'meta-1': '#DC3545',
//         'meta-2': '#EFF2F7',
//         'meta-3': '#10B981',
//         'meta-4': '#313D4A',
//         'meta-5': '#259AE6',
//         'meta-6': '#FFBA00',
//         'meta-7': '#FF6766',
//         'meta-8': '#F0950C',
//         'meta-9': '#E5E7EB',
//         success: '#219653',
//         danger: '#D34053',
//         warning: '#FFA70B',
//         // Design token colors - extending existing colors
//         'token-surface': 'var(--surface)',
//         'token-on-surface': 'var(--on-surface)',
//         'token-primary': 'var(--primary)',
//         'token-on-primary': 'var(--on-primary)',
//         'token-outline': 'var(--outline)',
//         'token-outline-soft': 'var(--outline-soft)',
//         'token-success': 'var(--status-success)',
//         'token-error': 'var(--status-error)',
//         'token-warning': 'var(--status-warning)',
//       },
//       spacing: {
//         'token-025': '0.125rem',
//         'token-050': '0.25rem',
//         'token-075': '0.375rem',
//         'token-100': '0.5rem',
//         'token-150': '0.75rem',
//         'token-200': '1rem',
//       },
//       borderRadius: {
//         'token-025': '0.125rem',
//         'token-050': '0.25rem',
//         'token-100': '0.5rem',
//         'token-200': '1rem',
//         'token-300': '1.5rem',
//       },
//       height: {
//         'screen/2': '50vh',
//         screen98: '98vh',
//         screen96: '96vh',
//         screen94: '94vh',
//         screen92: '92vh',
//       },
//     },
//   },
// };
const theme = tailwindConfig.theme.extend;
// Helper to create CSS variable with fallback
const cssVar = (varName, fallback) => `var(${varName}, ${fallback})`;
// Extract all design tokens from tailwind.config.js
// Using CSS fallback values to ensure colors work even when CSS variables aren't defined
export const tokens = {
    // Colors - with fallback values for environments where CSS variables aren't set
    surface: cssVar('--surface', '#f9fafb'),
    onSurface: cssVar('--on-surface', '#1f2937'),
    primary: cssVar('--primary', '#3b82f6'),
    onPrimary: cssVar('--on-primary', '#ffffff'),
    outline: cssVar('--outline', '#e5e7eb'),
    outlineSoft: cssVar('--outline-soft', '#f3f4f6'),
    success: cssVar('--status-success', '#10b981'),
    error: cssVar('--status-error', '#ef4444'),
    warning: cssVar('--status-warning', '#f59e0b'),
    red: theme.colors.red?.DEFAULT || '#ff0000',
    darkGray: theme.colors.grey_0 || '#4a4a4a',
    white: theme.colors.white || '#ffffff',
    // Spacing
    spacing025: theme.spacing['token-025'],
    spacing050: theme.spacing['token-050'],
    spacing075: theme.spacing['token-075'],
    spacing100: theme.spacing['token-100'],
    spacing150: theme.spacing['token-150'],
    spacing200: theme.spacing['token-200'],
    spacing300: theme.spacing['token-300'],
    spacing400: theme.spacing['token-400'],
    spacing500: theme.spacing['token-500'],
    spacing600: theme.spacing['token-600'],
    spacing800: theme.spacing['token-800'],
    spacing1000: theme.spacing['token-1000'],
    spacing1200: theme.spacing['token-1200'],
    // Border Radius
    borderRadius025: theme.borderRadius['token-025'],
    borderRadius050: theme.borderRadius['token-050'],
    borderRadius100: theme.borderRadius['token-100'],
    borderRadius200: theme.borderRadius['token-200'],
    borderRadius300: theme.borderRadius['token-300'],
    borderRadius400: theme.borderRadius['token-400'],
    borderRadiusNone: theme.borderRadius['token-none'],
    borderRadiusRound: theme.borderRadius['token-round'],
    // State Layer (from CSS variables, not in tailwind config)
    stateLayerNone: 'var(--state-layer-none)',
    stateLayerHover: 'var(--state-layer-hover)',
    stateLayerPress: 'var(--state-layer-press)',
};
