import React from 'react';
import './App.css';
import { MultiSelect, Autocomplete, AutocompleteGroupBy, } from './core-components';
function App() {
    return (React.createElement("div", { className: "flex flex-col gap-4" },
        React.createElement("p", { style: { margin: '0 0 10px 0' } }, "Autocomplete Comp."),
        React.createElement(MultiSelect, { options: ['UPI', 'CARD', 'CASH'], selectedItems: ['CASH', 'UPI'], onSelect: (item) => {
                console.log({ item });
            } }),
        React.createElement(Autocomplete, { value: "", onValueChange: () => { }, options: ['One', 'Two', 'Three', 'Four', 'Five', 'Six'] }),
        React.createElement(AutocompleteGroupBy, { data: [
                {
                    path: '/registration',
                    name: 'Registration',
                    title: 'REGISTRATION',
                    order: 1,
                    icon: 'RiUserAddLine',
                    children: [
                        {
                            path: '/registration/patient',
                            name: 'Patient Registration',
                            icon: 'FaAddressCard',
                            title: 'Patient Registration',
                        },
                        {
                            path: '/registration/client',
                            name: 'Client Registration',
                            icon: 'FaRegUser',
                            title: 'Client Registration',
                        },
                    ],
                },
                {
                    path: '/home-collection',
                    name: 'Home Collection',
                    title: 'HOME COLLECTION',
                    order: 7,
                    icon: 'BsFillCollectionFill',
                    badgeColor: '#ffffff',
                    children: [
                        {
                            path: '/home-collection/booking-chart',
                            name: 'Booking Chart',
                            icon: 'BiCommentDetail',
                            title: 'Booking Chart',
                        },
                        {
                            path: '/home-collection/collection-location',
                            name: 'Collection Location',
                            icon: 'BiCommentDetail',
                            title: 'Collection Location',
                        },
                        {
                            path: '/home-collection/field-executive',
                            name: 'Field Executive',
                            icon: 'BiCommentDetail',
                            title: 'Field Executive',
                        },
                        {
                            path: '/home-collection/field-executive',
                            name: 'Field Executive',
                            icon: 'BiCommentDetail',
                            title: 'Field Executive',
                        },
                        {
                            path: '/home-collection/route',
                            name: 'Route',
                            icon: 'BiCommentDetail',
                            title: 'Route',
                        },
                        {
                            path: '/home-collection/fe-allocation',
                            name: 'FE Allocation',
                            icon: 'BiCommentDetail',
                            title: 'FE Allocation',
                        },
                        {
                            path: '/home-collection/contact-information',
                            name: 'Contact Information',
                            icon: 'BiCommentDetail',
                            title: 'Contact Information',
                        },
                        {
                            path: '/home-collection/time-slot',
                            name: 'Time Slot',
                            icon: 'BiCommentDetail',
                            title: 'Time Slot',
                        },
                    ],
                },
                {
                    path: '/account-receivable',
                    name: 'Account Receivable',
                    title: 'ACCOUNT RECEIVABLE',
                    order: 2,
                    icon: 'MdAccountBalance',
                    children: [
                        {
                            path: '/account-receivable/transaction-details',
                            name: 'Transaction Details',
                            icon: 'RiCouponLine',
                            title: 'Transaction Details',
                        },
                        {
                            path: '/account-receivable/payment',
                            name: 'Payment',
                            icon: 'BsPiggyBank',
                            title: 'Payment',
                        },
                        {
                            path: '/account-receivable/open-batch',
                            name: 'Open Batch',
                            icon: 'MdOutlineBatchPrediction',
                            title: 'Open Batch',
                        },
                        {
                            path: '/account-receivable/receipt',
                            name: 'Receipt',
                            icon: 'BsReceipt',
                            title: 'Receipt',
                        },
                        {
                            path: '/account-receivable/bill-summary',
                            name: 'Bill Summary',
                            icon: 'IoReceiptOutline',
                            title: 'Bill Summary',
                        },
                    ],
                },
                {
                    path: '/sample-management',
                    name: 'Sample Management',
                    title: 'SAMPLE MANAGEMENT',
                    order: 12,
                    icon: 'TbTopologyStar3',
                    children: [
                        {
                            path: '/sample-management/phlebotomy',
                            name: 'Phlebotomy',
                            icon: 'BiCommentDetail',
                            title: 'Phlebotomy',
                        },
                    ],
                },
                {
                    path: '/result-entry',
                    name: 'Result Entry',
                    title: 'RESULT ENTRY',
                    order: 3,
                    icon: 'SiSentry',
                    children: [
                        {
                            path: '/result-entry/general',
                            name: 'General Result Entry',
                            icon: 'BiCategory',
                            title: 'General Result Entry',
                        },
                        {
                            path: '/result-entry/micro',
                            name: 'Micro Result Entry',
                            icon: 'GiMicroscope',
                            title: 'Micro Result Entry',
                        },
                        {
                            path: '/result-entry/histo',
                            name: 'Histo Result Entry',
                            icon: 'MdHistoryToggleOff',
                            title: 'Histo Result Entry',
                        },
                    ],
                },
                {
                    path: '/validation',
                    name: 'Validation',
                    title: 'PANEL APPROVAL',
                    order: 4,
                    icon: 'MdOutlineRule',
                    children: [
                        {
                            path: '/validation/panel-approval',
                            name: 'Panel Approval',
                            icon: 'MdOutlineApproval',
                            title: 'Panel Approval',
                        },
                    ],
                },
                {
                    path: '/patient-reports',
                    name: 'Patient Reports',
                    title: 'PATIENT REPORTS',
                    order: 5,
                    icon: 'MdOutlineLibraryBooks',
                    children: [
                        {
                            path: '/patient-reports/generate-report',
                            name: 'Generate Report',
                            icon: 'GiRegeneration',
                            title: 'Generate Report',
                        },
                        {
                            path: '/patient-reports/delivery-queue',
                            name: 'Delivery Queue',
                            icon: 'MdOutlineDeliveryDining',
                            title: 'Delivery Queue',
                        },
                    ],
                },
                {
                    path: '/communication',
                    name: 'Communication',
                    title: 'EDI ENGINE',
                    order: 6,
                    icon: 'FaCommentDots',
                    children: [
                        {
                            path: '/communication/interface-manager',
                            name: 'Interface Manager',
                            icon: 'CgCommunity',
                            title: 'Interface Manager',
                        },
                        {
                            path: '/communication/mapping/conversation-mapping',
                            name: 'Conversation Mapping',
                            icon: 'GiConversation',
                            title: 'Conversation Mapping',
                        },
                        {
                            path: '/communication/host-communication',
                            name: 'Host Communication',
                            icon: 'RiGhostSmileLine',
                            title: 'Host Communication',
                        },
                        {
                            path: '/communication/mapping/segment-mapping',
                            name: 'Data Segment Mapping',
                            icon: 'GiDatabase',
                            title: 'Data Segment Mapping',
                        },
                        {
                            path: '/communication/instrument-result-mapping',
                            name: 'Instrument Result Mapping',
                            icon: 'VscOutput',
                            title: 'Instrument Result Mapping',
                        },
                        {
                            path: '/communication/transmitted-message',
                            name: 'Transmitted Message',
                            icon: 'AiOutlineMessage',
                            title: 'Transmitted Message',
                        },
                    ],
                },
                {
                    path: '/collection',
                    name: 'Collection',
                    title: 'MASTER SETUP',
                    order: 7,
                    icon: 'BsFillCollectionFill',
                    badgeColor: '#ffffff',
                    children: [
                        {
                            path: '/collection/banner',
                            name: 'Banner',
                            icon: 'ImImages',
                            title: 'Banner',
                        },
                        {
                            path: '/collection/lab',
                            name: 'Lab',
                            icon: 'ImLab',
                            title: 'Lab',
                        },
                        {
                            path: '/collection/deginisation',
                            name: 'Deginisation',
                            icon: 'FaUserMd',
                            title: 'Deginisation',
                        },
                        {
                            path: '/collection/department',
                            name: 'Department',
                            icon: 'FcDepartment',
                            title: 'Department',
                        },
                        {
                            path: '/collection/master-analyte',
                            name: 'Analyte Master',
                            icon: 'IoMdAnalytics',
                            title: 'Analyte Master',
                        },
                        {
                            path: '/collection/test-analyte-mapping',
                            name: 'Test Analyte Mapping',
                            icon: 'IoIosAnalytics',
                            title: 'Test Analyte Mapping',
                        },
                        {
                            path: '/collection/master-panel',
                            name: 'Panel Master',
                            icon: 'FaSolarPanel',
                            title: 'Panel Master',
                        },
                        {
                            path: '/collection/test-panel-mapping',
                            name: 'Test Panel Mapping',
                            icon: 'FaLayerGroup',
                            title: 'Test Panel Mapping',
                        },
                        {
                            path: '/collection/master-package',
                            name: 'Package Master',
                            icon: 'FiPackage',
                            title: 'Package Master',
                        },
                        {
                            path: '/collection/test-master',
                            name: 'Test Master',
                            icon: 'SiMinetest',
                            title: 'Test Master',
                        },
                        {
                            path: '/collection/section',
                            name: 'Section',
                            icon: 'BsGrid3X3',
                            title: 'Section',
                        },
                        {
                            path: '/collection/sample-container',
                            name: 'Sample Container',
                            icon: 'AiOutlineContainer',
                            title: 'Sample Container',
                        },
                        {
                            path: '/collection/sample-type',
                            name: 'Sample Type',
                            icon: 'FaBuromobelexperte',
                            title: 'Sample Type',
                        },
                        {
                            path: '/collection/test-sample-mapping',
                            name: 'Test Sample Mapping',
                            icon: 'IoIosGitCompare',
                            title: 'Test Sample Mapping',
                        },
                        {
                            path: '/collection/methods',
                            name: 'Methods',
                            icon: 'VscSymbolMethod',
                            title: 'Methods',
                        },
                        {
                            path: '/collection/doctors',
                            name: 'Doctors',
                            icon: 'GiHospitalCross',
                            title: 'Doctors',
                        },
                        {
                            path: '/collection/registration-locations',
                            name: 'Registartion Locations',
                            icon: 'RiMap2Line',
                            title: 'Registartion Locations',
                        },
                        {
                            path: '/collection/corporate-clients',
                            name: 'Corporate Clients',
                            icon: 'FiUsers',
                            title: 'Corporate Clients',
                        },
                        {
                            path: '/collection/delivery-schedule',
                            name: 'Delivery Schedule',
                            icon: 'AiOutlineSchedule',
                            title: 'Delivery Schedule',
                        },
                        {
                            path: '/collection/administrative-divisions',
                            name: 'Administrative Divisions',
                            icon: 'FaAddressCard',
                            title: 'Administrative Divisions',
                        },
                        {
                            path: '/collection/sales-team',
                            name: 'Sales Team',
                            icon: 'RiTeamLine',
                            title: 'Sales Team',
                        },
                        {
                            path: '/collection/possible-results',
                            name: 'Possible Results',
                            icon: 'AiOutlineSolution',
                            title: 'Possible Results',
                        },
                        {
                            path: '/collection/library',
                            name: 'Library',
                            icon: 'HiLibrary',
                            title: 'Library',
                        },
                        {
                            path: '/collection/price-list',
                            name: 'PriceList',
                            icon: 'GiPriceTag',
                            title: 'PriceList',
                        },
                        {
                            path: '/collection/reference-ranges',
                            name: 'ReferenceRanges',
                            icon: 'VscReferences',
                            title: 'ReferenceRanges',
                        },
                        {
                            path: '/collection/comment-manager',
                            name: 'Comment Manager',
                            icon: 'BiCommentDetail',
                            title: 'Comment Manager',
                        },
                        {
                            path: '/collection/tat-master',
                            name: 'TAT Settings',
                            icon: 'BiCommentDetail',
                            title: 'TAT Settings',
                        },
                        {
                            path: '/collection/holiday-master',
                            name: 'Holiday Master',
                            icon: 'BiCommentDetail',
                            title: 'Holiday Master',
                        },
                    ],
                },
                {
                    path: '/workflow-manager',
                    name: 'Workflow Manager',
                    title: 'WORKFLOW MANAGER',
                    order: 11,
                    icon: 'TbTopologyStar3',
                    children: [
                        {
                            path: '/workflow-manager/sample-workflow',
                            name: 'Sample Workflow',
                            icon: 'BiCommentDetail',
                            title: 'Sample Workflow',
                        },
                    ],
                },
                {
                    path: '/settings',
                    name: 'Settings',
                    title: 'APPLICATION SETTING',
                    order: 8,
                    icon: 'RiSettings5Fill',
                    children: [
                        {
                            path: '/settings/role',
                            name: 'Role',
                            icon: 'GiKeyring',
                            title: 'Role',
                        },
                        {
                            path: '/settings/users',
                            name: 'User',
                            icon: 'FaUsersCog',
                            title: 'User',
                        },
                        {
                            path: '/settings/login-activity',
                            name: 'Login Activity',
                            icon: 'FiActivity',
                            title: 'Login Activity',
                        },
                        {
                            path: '/settings/mapping/role-mapping',
                            name: 'Role Mapping',
                            icon: 'RiShieldKeyholeFill',
                            title: 'Role Mapping',
                        },
                        {
                            path: '/settings/shortcut-menu',
                            name: 'Shortcut Menu',
                            icon: 'CgShortcut',
                            title: 'Shortcut Menu',
                        },
                        {
                            path: '/settings/environment',
                            name: 'Environment',
                            icon: 'MdSettingsInputComponent',
                            title: 'Environment',
                        },
                        {
                            path: '/settings/notice-boards',
                            name: 'Notice Boards',
                            icon: 'FaClipboardList',
                            title: 'Notice Boards',
                        },
                        {
                            path: '/settings/company',
                            name: 'Company',
                            icon: 'HiOutlineOfficeBuilding',
                            title: 'Company',
                        },
                        {
                            path: '/settings/lookup',
                            name: 'Lookup',
                            icon: 'MdLooks',
                            title: 'Lookup',
                        },
                        {
                            path: '/settings/field-wise-control',
                            name: 'Field Wise Control',
                            icon: 'MdLooks',
                            title: 'Field Wise Control',
                        },
                    ],
                },
                {
                    path: '/report-builder',
                    name: 'Report Builder',
                    title: 'REPORT BUILDER',
                    order: 9,
                    icon: 'HiDocumentReport',
                    children: [
                        {
                            path: '/report-builder/report-settings',
                            name: 'Report Settings',
                            icon: 'RiListSettingsFill',
                            title: 'Report Settings',
                        },
                        {
                            path: '/report-builder/report-template',
                            name: 'Report Template',
                            icon: 'ImInsertTemplate',
                            title: 'Report Template',
                        },
                    ],
                },
                {
                    path: '/enquiry',
                    name: 'Enquiry',
                    title: 'ENQUIRY',
                    order: 10,
                    icon: 'TbTopologyStar3',
                    children: [
                        {
                            path: '/enquiry/event-log',
                            name: 'Event Log',
                            icon: 'MdOutlineEventNote',
                            title: 'Event Log',
                        },
                    ],
                },
            ] })));
}
export default App;
